name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: yarn install
      - run: yarn compile
      - run: yarn format --check
      - run: yarn lint --max-warnings 0
      - name: Install gnome-extensions
        run: |
          sudo apt-get -q update
          sudo apt-get -y install gnome-shell
      - run: yarn package
