name: Release

on:
  push:
    tags:
      - v*

jobs:
  github-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: yarn install
      - run: yarn compile
      - name: apt-get install gnome-shell
        run: |
          sudo apt-get -q update
          sudo apt-get -qq -y install gnome-shell
      - run: yarn package
      - uses: softprops/action-gh-release@v1
        with:
          files: jetbrains-search-provider@swsnr.de.shell-extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
